apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce.fullname" . }}-secrets
  labels:
    {{ include "ecommerce.labels" . | nindent 4 }}
type: Opaque
data:
  admin-username: {{ "admin" | b64enc }}
  admin-password: {{ "adminpassword" | b64enc }}