spring:
  application:
    name: product-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/product
    username: admin
    password: admin123
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 30m
  flyway:
    url: jdbc:postgresql://localhost:5432/product
    user: admin
    password: admin123
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    redis:
      enabled: true
    db:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      exchangeRateService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  timelimiter:
    instances:
      exchangeRateService:
        timeoutDuration: 3s

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.data.r2dbc: INFO
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO
    reactor.kafka: INFO
    io.projectreactor: INFO