name: CI

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 21 (Azul)
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Prepare Docker Network
        run: |
          chmod +x ./fix-docker-networking.sh
          ./fix-docker-networking.sh

      - name: Run simple PostgreSQL test
        run: |
          cd customer-write
          mvn -Dtest=SimplePostgresTest test -Dtestcontainers.ryuk.disabled=true -Dtestcontainers.checks.disable=true
        continue-on-error: true

      - name: Build and run tests
        run: |
          export MAVEN_OPTS="-Dtestcontainers.ryuk.disabled=true -Dtestcontainers.checks.disable=true -Djava.net.preferIPv4Stack=true"
          mvn clean verify -Dtestcontainers.ryuk.disabled=true -DskipTests

      - name: Run tests with debugging
        run: |
          export MAVEN_OPTS="-Dtestcontainers.ryuk.disabled=true -Dtestcontainers.checks.disable=true -Djava.net.preferIPv4Stack=true"
          mvn test -Dtestcontainers.ryuk.disabled=true -Dtestcontainers.checks.disable=true -Dspring.profiles.active=test -DforkCount=0

      - name: Run unit tests only
        if: ${{ failure() }}
        run: |
          # Uruchomienie tylko testów jednostkowych jako plan awaryjny
          mvn test -Dtest="*Test" -DexcludedGroups="integration" -DforkCount=0