name: CI

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 21 (Azul)
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set Testcontainers host override
        run: |
          echo "TESTCONTAINERS_HOST_OVERRIDE=$(ip route | awk '/default/ { print $3 }')" >> $GITHUB_ENV

      - name: Build and run tests
        run: mvn clean verify
