global:
  scrape_interval: 15s  # Jak często Prometheus zbiera dane (domyślnie 15s)

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'ecommerce-service'
    static_configs:
      - targets: ['ecommerce-service:8080']
