{{- if .Values.infrastructure.alertmanager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infrastructure.fullname" . }}-{{ .Values.infrastructure.alertmanager.configMap.name }}
  labels:
    {{ include "infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
data:
  {{ toYaml .Values.infrastructure.alertmanager.configMap.data | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infrastructure.fullname" . }}-alertmanager
  labels:
    {{ include "infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  type: {{ .Values.infrastructure.alertmanager.service.type }}
  ports:
    - port: {{ .Values.infrastructure.alertmanager.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{ include "infrastructure.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "infrastructure.fullname" . }}-alertmanager
  labels:
    {{ include "infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  serviceName: {{ include "infrastructure.fullname" . }}-alertmanager
  replicas: 1
  selector:
    matchLabels:
      {{ include "infrastructure.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: alertmanager
  template:
    metadata:
      labels:
        {{ include "infrastructure.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: alertmanager
    spec:
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: alertmanager
          image: "{{ .Values.infrastructure.alertmanager.image.repository }}:{{ .Values.infrastructure.alertmanager.image.tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
          ports:
            - containerPort: 9093
              name: web
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager
            - name: alertmanager-data
              mountPath: /alertmanager
          resources:
            {{ toYaml .Values.infrastructure.alertmanager.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: web
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /-/ready
              port: web
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 3
      volumes:
        - name: alertmanager-config
          configMap:
            name: {{ include "infrastructure.fullname" . }}-{{ .Values.infrastructure.alertmanager.configMap.name }}
  volumeClaimTemplates:
    - metadata:
        name: alertmanager-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.global.storageClass }}
        resources:
          requests:
            storage: {{ .Values.infrastructure.alertmanager.persistence.size }}
{{- end }}