{{- if .Values.infrastructure.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infrastructure.fullname" . }}-kibana
  labels:
    {{ include "infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
spec:
  type: {{ .Values.infrastructure.kibana.service.type }}
  ports:
    - port: {{ .Values.infrastructure.kibana.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ include "infrastructure.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infrastructure.fullname" . }}-kibana
  labels:
    {{ include "infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "infrastructure.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kibana
  template:
    metadata:
      labels:
        {{ include "infrastructure.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kibana
    spec:
      containers:
        - name: kibana
          image: "{{ .Values.infrastructure.kibana.image.repository }}:{{ .Values.infrastructure.kibana.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5601
              name: http
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.infrastructure.kibana.environment.ELASTICSEARCH_HOSTS }}
          resources:
            {{ toYaml .Values.infrastructure.kibana.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
{{- end }}