{{- if .Values.infrastructure.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infrastructure.fullname" . }}-{{ .Values.infrastructure.prometheus.configMap.name | default "prometheus-config" }}
  labels:
    {{ include "infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  {{- if .Values.infrastructure.prometheus.configMap.data }}
  {{ toYaml .Values.infrastructure.prometheus.configMap.data | nindent 2 }}
  {{- else }}
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infrastructure.fullname" . }}-prometheus
  labels:
    {{ include "infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.infrastructure.prometheus.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.infrastructure.prometheus.service.port | default 9090 }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{ include "infrastructure.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "infrastructure.fullname" . }}-prometheus
  labels:
    {{ include "infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  serviceName: {{ include "infrastructure.fullname" . }}-prometheus
  replicas: 1
  selector:
    matchLabels:
      {{ include "infrastructure.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{ include "infrastructure.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: prometheus
          image: "{{ .Values.infrastructure.prometheus.image.repository | default "prom/prometheus" }}:{{ .Values.infrastructure.prometheus.image.tag | default "v2.40.0" }}"
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/usr/share/prometheus/console_libraries
            - --web.console.templates=/usr/share/prometheus/consoles
          ports:
            - containerPort: 9090
              name: web
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
          resources:
            {{- if .Values.infrastructure.prometheus.resources }}
            {{ toYaml .Values.infrastructure.prometheus.resources | nindent 12 }}
            {{- else }}
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
            {{- end }}
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: web
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /-/ready
              port: web
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 3
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ include "infrastructure.fullname" . }}-{{ .Values.infrastructure.prometheus.configMap.name | default "prometheus-config" }}
  volumeClaimTemplates:
    - metadata:
        name: prometheus-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.global.storageClass | default "standard" }}
        resources:
          requests:
            storage: {{ .Values.infrastructure.prometheus.persistence.size | default "10Gi" }}
{{- end }}