apiVersion: v1
kind: Service
metadata:
  name: {{ include "customer-write.fullname" . }}
  labels:
    {{ include "customer-write.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ include "customer-write.selectorLabels" . | nindent 4 }}