# Fragment konfiguracji dla application.yml

spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1ms
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:}
      timeout: 2000

cache:
  product:
    ttl: 1800  # 30 minut w sekundach
    enabled: true
  featured-products:
    ttl: 900   # 15 minut w sekundach
    enabled: true
  category:
    ttl: 3600  # 1 godzina w sekundach
    enabled: true