server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
    listener:
      ack-mode: MANUAL

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/eventstore?authSource=admin
      database: eventstore
      field-naming-strategy: org.springframework.data.mapping.model.CamelCaseAbbreviatingFieldNamingStrategy
      auto-index-creation: true
      dot-replacement: _

event:
  listener:
    group-id: event-store
    topics:
      -customer.registered.event
      -customer.updated.event
      -customer.deleted.event
      -product.created.event
      -product.updated.event
      -vendor.registered.event
      -vendor.updated.event

---
# 🔹 Konfiguracja dla DEV
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/eventstore_dev?authSource=admin
      database: eventstore_dev
      field-naming-strategy: org.springframework.data.mapping.model.CamelCaseAbbreviatingFieldNamingStrategy
      auto-index-creation: true
      dot-replacement: _

---
# 🔹 Konfiguracja dla TEST
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/eventstore_test?authSource=admin
      database: eventstore_test
      auto-index-creation: true

---
# 🔹 Konfiguracja dla PROD
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://eventstore:password@mongo-prod-server:27017/eventstore
      database: eventstore
      auto-index-creation: true
