filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.json
    json.keys_under_root: true
    json.message_key: message

processors:
  - add_docker_metadata: ~
  - add_host_metadata: ~

output.logstash:
  hosts: ["logstash:5000"]

setup.kibana:
  host: "kibana:5601"

logging.level: debug