global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'twoja_nazwa_uzytkownika'
  smtp_auth_password: 'twoje_haslo'

route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'default'
    email_configs:
      - to: 'alerts@example.com'
        send_resolved: true
