apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alertmanager@example.com'
      smtp_auth_username: 'alertmanager'
      smtp_auth_password: 'password'

    route:
      receiver: 'slack-notifications'
      group_by: ['alertname', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h

      routes:
        - match:
            severity: critical
          receiver: 'pagerduty'
          continue: true
        
        - match:
            service: customer-read
          receiver: 'team-customer'

    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - channel: '#alerts'
            send_resolved: true
            title: '{{ template "slack.default.title" . }}'
            text: '{{ template "slack.default.text" . }}'
      
      - name: 'pagerduty'
        pagerduty_configs:
          - service_key: YOUR_PAGERDUTY_SERVICE_KEY
            send_resolved: true
      
      - name: 'team-customer'
        slack_configs:
          - channel: '#team-customer-alerts'
            send_resolved: true
            title: '{{ template "slack.default.title" . }}'
            text: '{{ template "slack.default.text" . }}'
        email_configs:
          - to: 'customer-team@example.com'
            send_resolved: true

    templates:
      - '/etc/alertmanager/template/*.tmpl'