name: CI

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Set up Docker network and configure Kafka
        run: |
          chmod +x .github/workflows/ci/setup-kafka.sh
          .github/workflows/ci/setup-kafka.sh

      - name: Build all modules
        run: mvn --batch-mode clean install -DskipTests

      - name: Run tests in customer-write
        run: mvn --batch-mode test -pl customer-write -Dsurefire.failIfNoSpecifiedTests=false -Dtestcontainers.ryuk.disabled=true -DCI=true

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build customer-read Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/customer-read:latest -f customer-read/Dockerfile .

      - name: Build customer-write Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/customer-write:latest -f customer-write/Dockerfile .

      - name: Push customer-read to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/customer-read:latest

      - name: Push customer-write to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/customer-write:latest
