name: CI

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Disable TestContainers Ryuk and configure network
        run: |
          echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV
          sudo sh -c 'echo "127.0.0.1 host.testcontainers.internal" >> /etc/hosts'
          sudo sh -c 'echo "127.0.0.1 kafka" >> /etc/hosts'
          mkdir -p ~/.testcontainers
          echo "ryuk.container.enabled=false" > ~/.testcontainers/testcontainers.properties
          echo "host.testcontainers.internal.host=localhost" >> ~/.testcontainers/testcontainers.properties

      - name: Build all modules
        run: mvn --batch-mode clean install -DskipTests

      - name: Run tests in customer-write
        run: mvn --batch-mode test -pl customer-write -Dsurefire.failIfNoSpecifiedTests=false -Dtestcontainers.ryuk.disabled=true