# Common configuration for all profiles
spring:
  application:
    name: customer-write
  main:
    web-application-type: reactive

  # JDBC configuration for event store
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      pool-name: CustomerWriteHikariPool

  # Flyway migration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Kafka configuration for event publishing
  kafka:
    bootstrap-servers: localhost:29092
    schema-registry-url: http://localhost:8081
    producer:
      observation-enabled: true
      retries: 3
      properties:
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        retry.backoff.ms: 500
    consumer:
      observation-enabled: true
    listener:
      observation-enabled: true

# Server settings
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Logging configuration
logging:
  logstash:
    host: ${LOGSTASH_HOST:localhost}
    port: ${LOGSTASH_PORT:5000}
  level:
    root: INFO
    pl.ecommerce: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    propagation:
      type: w3c
  observations:
    http:
      server:
        requests:
          enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:default}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99


# OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: pl.ecommerce.customer.write.api

# Event listener configuration
event:
  listener:
    group-id: ${spring.application.name}-group
    topics:
      - customer.registered.event
      - customer.updated.event
      - customer.email-changed.event
      - customer.email-verified.event
      - customer.phone-verified.event
      - customer.address-added.event
      - customer.address-updated.event
      - customer.address-removed.event
      - customer.preferences-updated.event
      - customer.deactivated.event
      - customer.reactivated.event
      - customer.deleted.event

# Alerting configuration
alerts:
  enabled: true
  evaluation-interval: 15s
  critical-email-recipients: operations@example.com,oncall@example.com
  slack-webhook-url: ${SLACK_WEBHOOK_URL:}

# Kafka DLQ configuration
kafka:
  dlq:
    enabled: true
    retry-attempts: 3
    initial-interval-ms: 1000
    multiplier: 2.0
    max-interval-ms: 60000
    retry-interval-ms: 60000
    topics: customer.registered.event.DLT,customer.updated.event.DLT,customer.email-changed.event.DLT,customer.email-verified.event.DLT,customer.phone-verified.event.DLT,customer.address-added.event.DLT,customer.address-updated.event.DLT,customer.address-removed.event.DLT,customer.preferences-updated.event.DLT,customer.deactivated.event.DLT,customer.reactivated.event.DLT,customer.deleted.event.DLT

opentelemetry:
  sdk:
    disabled: false
  service:
    name: ${spring.application.name}
  traces:
    exporter: otlp
  metrics:
    exporter: prometheus
  otlp:
    endpoint: http://otel-collector:4317
    protocol: grpc
